framework:
    messenger:
        # reset services after consuming messages
        failure_transport: failed
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 10
                    # milliseconds delay = 1 seg
                    delay: 1000
                    max_delay: 30000
                    multiplier: 4
            failed:
                dsn: '%env(FAILURE_MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 20
                    # milliseconds delay = 1 seg
                    delay: 30000
                    max_delay: 86400000
                    multiplier: 3

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Application\Company\Command\RequestAuthenticationTraCommand': async
