nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
        host_patterns:
            - ^api\.
    documentation:
        info:
            title: Simplify auth service
            description: This is the security auth service for Simplify
            version: 1.1.1
        servers:
            - url: /service/auth
              description: (Integration server)
            - url: /api/v1
              description: (Developer server)
        paths:
            /user/login:
                post:
                    tags:
                        - User
                    description: User Login
                    operationId: userLogin
                    requestBody:
                        description: The user to authenticate in Simplify
                        required: true
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/UserLoginRequest'
                    responses:
                        200:
                            description: Login authenticated
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/UserLoginResponse'
                        400:
                            description: Bad Request
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/BadRequest'
                        401:
                            $ref: '#/components/responses/UnauthorizedError'
                        403:
                            description: Forbidden
                        default:
                            description: Unexpected error

            /user/token/refresh:
                post:
                    tags:
                        - User Refresh Token
                    description: User Refresh Token
                    operationId: userRefreshToken
                    requestBody:
                        description: The refresh token to regenerated JWT login for Simplify
                        required: true
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/UserRefreshTokenRequest'
                    responses:
                        '200':
                            description: Login authenticated
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/UserLoginResponse'
                        '401':
                            description: Access token is missing or invalid
        components:
            schemas:
                UserLoginRequest:
                    type: object
                    required:
                        - username
                        - password
                    properties:
                        username:
                            type: string
                            format: email
                            example: 'john.doe@example.co.tz'
                            maxLength: 200
                        password:
                            type: string
                            example: 'str0n9Pa$$w0rD'
                            minLength: 8
                            maxLength: 200
                UserRefreshTokenRequest:
                    type: object
                    required:
                        - refresh_token
                    properties:
                        refresh_token:
                            type: string
                            maxLength: 200
                UserLoginResponse:
                    type: object
                    required:
                        - token
                        - refresh_token
                    properties:
                        token:
                            type: string
                            example: 'very-long-chain'
                        refresh_token:
                            type: string
                            example: 'long-chain'
                BadRequest:
                    type: object
                    required:
                        - errors
                    properties:
                        errors:
                            type: object
            responses:
                UnauthorizedError:
                    description: the access token has expired or identity not authenticated
