nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
        host_patterns:
            - ^api\.
    documentation:
        info:
            title: Simplify auth service
            description: This is the secutiry auth service for Simplify
            version: 1.1.0
        servers:
            - url: /api/v1
        paths:
            /user/login:
                post:
                    tags:
                        - User
                    description: User Login
                    operationId: userLogin
                    requestBody:
                        description: The user to authenticate in Simplify
                        required: true
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/UserLoginRequest'
                    responses:
                        200:
                            description: Login authenticated
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/UserLoginResponse'
                        400:
                            description: Bad Request
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/BadRequest'
                        401:
                            $ref: '#/components/responses/UnauthorizedError'
                        403:
                            description: Forbidden
                        default:
                            description: Unexpected error
            /user/token/refresh:
                post:
                    security:
                        - bearerAuth: [ ]
                    tags:
                        - User Refresh Token
                    description: User Refresh Token
                    operationId: userRefreshToken
                    parameters:
                        - in: header
                          name: Authorization
                          schema:
                              type: bearer
                              format: string
                          required: true
                    responses:
                        '200':
                            description: Success
                        '401':
                            description: Access token is missing or invalid
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    description: "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\""
            schemas:
                UserLoginRequest:
                    type: object
                    required:
                        - username
                        - password
                    properties:
                        username:
                            type: string
                            format: email
                            maxLength: 200
                        password:
                            type: string
                            maxLength: 200
                            minLength: 8
                UserLoginResponse:
                    type: object
                    required:
                        - token
                        - refresh_token
                    properties:
                        token:
                            type: string
                        refresh_token:
                            type: string
                BadRequest:
                    type: object
                    required:
                        - errors
                    properties:
                        errors:
                            type: object
            responses:
                UnauthorizedError:
                    description: the access token has expired or identity not authenticated

