version: "3.4"

services:
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: dev
        volumes:
            - .:/app
        command: sh -c 'composer install --no-interaction --optimize-autoloader && php -S 0.0.0.0:8000 -t public'
        ports:
            - ${CONTAINER_PORT}:8000
        depends_on:
            - mysql
    mysql:
        image: mariadb:10.3.31
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: com.simplify.api.v1.auth
            MYSQL_ROOT_PASSWORD: password
