version: "3.4"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: prod
    volumes:
      - ./public:/app/public
    depends_on:
      - php-fpm
    ports:
      - ${CONTAINER_PORT}:443
    restart: always
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      target: prod
    volumes:
      - .:/app
    command: sh -c '/usr/bin/supervisord -n -c /etc/supervisord.conf'
    restart: always
