version: "3.4"

services:
  nginx:
    container_name: ${CONTAINER_NAME}_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: prod
    volumes:
      - app_volume:/app
    depends_on:
      - php-fpm
    ports:
      - ${CONTAINER_PORT}:80
    restart: always

  php-fpm:
    container_name: ${CONTAINER_NAME}_php
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      target: prod
    volumes:
      - app_volume:/app
      - ./var/log:/app/var/log
    command: sh -c '/usr/bin/supervisord -n -c /etc/supervisord.conf'
    restart: always

volumes:
  app_volume:
    name: ${CONTAINER_NAME}_volume

networks:
  default:
    name: ${CONTAINER_NETWORK}
    external: true
