version: "3.4"

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
    volumes:
      - .:/app
    command: sh -c 'composer install --no-interaction --optimize-autoloader && php -S localhost:8000'
    ports:
      - ${CONTAINER_PORT}:8000
    depends_on:
      - mysql
  mysql:
    image: mariadb:${MYSQL_VERSION}
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
