version: "3.4"

services:
  app:
    container_name: ${CONTAINER_NAME}_app
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: prod
    volumes:
      - app_volume:/app
      - ./var/log:/app/var/log
    command: sh -c '/usr/bin/supervisord'
    ports:
      - ${CONTAINER_PORT}:80
    restart: always

volumes:
  app_volume:
    name: ${CONTAINER_NAME}_volume

networks:
  default:
    name: ${CONTAINER_NETWORK}
    external: true
