controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

user:
    resource: ../../src/Infrastructure/Symfony/Api/User/Controller/
    prefix: /api/v1/user
    type: annotation

company:
    resource: ../../src/Infrastructure/Symfony/Api/Company/Controller/
    prefix: /api/v1/company
    type: annotation
