controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

user:
    resource: ../../src/Infrastructure/Symfony/Api/User/V1/Controller/
    prefix: /api/v1/user
    type: annotation

user_v2:
    resource: ../../src/Infrastructure/Symfony/Api/User/V2/Controller/
    prefix: /api/v2/user
    type: annotation

company:
    resource: ../../src/Infrastructure/Symfony/Api/Company/V1/Controller/
    prefix: /api/v1/company
    type: annotation

company_v2:
    resource: ../../src/Infrastructure/Symfony/Api/Company/V2/Controller/
    prefix: /api/v2/company
    type: annotation

organization:
    resource: ../../src/Infrastructure/Symfony/Api/Organization/V1/Controller/
    prefix: /api/v1/organization
    type: annotation
