controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

user:
    resource: ../../src/Infrastructure/Symfony/Api/User/Controller/
    prefix: /api/v1/user
    type: annotation

user_v2:
    resource: ../../src/Infrastructure/Symfony/Api/User/Controller/V2
    prefix: /api/v2/user
    type: annotation

company:
    resource: ../../src/Infrastructure/Symfony/Api/Company/Controller/
    prefix: /api/v1/company
    type: annotation

company_v2:
    resource: ../../src/Infrastructure/Symfony/Api/Company/Controller/V2
    prefix: /api/v2/company
    type: annotation
