#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
    path: /api/v1/user/login
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path:       /api/v1/user/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh