#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /api/v1/user/login
    methods: ['POST']

login_v2:
    path: /api/v2/user/login
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path: /api/v1/user/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
    methods: ['POST']

gesdinet_jwt_refresh_token_v2:
    path: /api/v2/user/token/refresh
    controller: App\Infrastructure\Symfony\Api\User\Controller\V2\RefreshTokenController::refresh
    methods: ['POST']
